extraction:
  cpp:
    after_prepare:
      - wget --no-check-certificate http://ftp.gnu.org/gnu/bison/bison-3.6.1.tar.gz
      - mkdir $HOME/bison
      - tar -xf bison-3.6.1.tar.gz; cd bison-3.6.1; ./configure --prefix=$HOME/bison; make -j 4 install; cd $PWD/..;
      - export PATH=$HOME/bison/bin:$PATH
    configure:
      command:
        - mkdir cmake
        - wget -qO- https://github.com/Kitware/CMake/releases/download/v3.15.0/cmake-3.15.0-Linux-x86_64.tar.gz | tar xpoz -C cmake --strip-components 1
        - mkdir build
        - cd build
        - ../cmake/bin/cmake ..
    index:
      build_command:
        - cd build
        - make