language: cpp

before_install:
  - sudo apt-get -y install bison

addons:
  apt:
    update: true
    packages:
      - bison
      - flex

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
