language: cpp
dist: focal

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - cd ..
  - ./build/all_tests
  
after_success:
  - coveralls -i src -e src/main.cpp -e src/scanner.l -e src/parser.y --gcov-options '\-lp'
